version: '3.4'

services:
  blankdb:
    image: postgres:14.2-alpine
    restart: always
    container_name: blankdb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - ./rabbitmq/logs:/var/log/rabbitmq/log
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest

  mongemini.service.api:
    image: ${DOCKER_REGISTRY-}mongeminiserviceapi
    build:
      context: .
      dockerfile: src/service/Mongemini.Service.API/Dockerfile
    depends_on:
      - blankdb
      - rabbitmq