#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["src/service/Mongemini.Service.API/Mongemini.Service.API.csproj", "src/service/Mongemini.Service.API/"]
RUN dotnet restore "src/service/Mongemini.Service.API/Mongemini.Service.API.csproj"
COPY . .
WORKDIR "/src/src/service/Mongemini.Service.API"
RUN dotnet build "Mongemini.Service.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Mongemini.Service.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Mongemini.Service.API.dll"]